package com.hust.kstn;

public class Aims {

    // These DVDs are generated by Gemini. Sorry but I don't find it
	// interesting to type each by hand.
    private static final DigitalVideoDisc[] availableDVDs = {
        new DigitalVideoDisc("The Lion King", "Animation", "Roger Allers", 87, 19.95),
        new DigitalVideoDisc("Star Wars", "Science Fiction", "George Lucas", 87, 24.95),
        new DigitalVideoDisc("Aladdin", "Animation", "Ron Clements", 90, 15.50),
        new DigitalVideoDisc("The Dark Knight", "Action", "Christopher Nolan", 152, 29.99),
        new DigitalVideoDisc("Pulp Fiction", "Crime", "Quentin Tarantino", 154, 17.80),
        new DigitalVideoDisc("Inception", "Science Fiction", "Christopher Nolan", 148, 22.50),
        new DigitalVideoDisc("Forrest Gump", "Drama", "Robert Zemeckis", 142, 14.95),
        new DigitalVideoDisc("Finding Nemo", "Animation", "Andrew Stanton", 100, 16.99),
        new DigitalVideoDisc("The Matrix", "Science Fiction", "Lana Wachowski", 136, 18.00),
        new DigitalVideoDisc("The Godfather", "Crime", "Francis Ford Coppola", 175, 26.90),
        new DigitalVideoDisc("Titanic", "Romance", "James Cameron", 195, 12.50),
        new DigitalVideoDisc("Avatar", "Science Fiction", "James Cameron", 162, 21.00),
        new DigitalVideoDisc("Jurassic Park", "Adventure", "Steven Spielberg", 127, 13.99),
        new DigitalVideoDisc("Shrek", "Animation", "Andrew Adamson", 90, 11.95),
        new DigitalVideoDisc("Gladiator", "Historical", "Ridley Scott", 155, 19.50),
        new DigitalVideoDisc("Toy Story", "Animation", "John Lasseter", 81, 15.00),
        new DigitalVideoDisc("Frozen", "Animation", "Chris Buck", 102, 18.25),
        new DigitalVideoDisc("Interstellar", "Science Fiction", "Christopher Nolan", 169, 23.75),
        new DigitalVideoDisc("E.T. the Extra-Terrestrial", "Science Fiction", "Steven Spielberg", 115, 10.99),
        new DigitalVideoDisc("Spirited Away", "Fantasy", "Hayao Miyazaki", 125, 25.00),
        new DigitalVideoDisc("The Avengers", "Action", "Joss Whedon", 143, 20.00),
        new DigitalVideoDisc("The Martian", "Science Fiction", "Ridley Scott", 144, 16.50),
        new DigitalVideoDisc("The Silence of the Lambs", "Horror", "Jonathan Demme", 118, 16.00),
        new DigitalVideoDisc("Whiplash", "Drama", "Damien Chazelle", 106, 17.50),
        new DigitalVideoDisc("Mad Max: Fury Road", "Action", "George Miller", 120, 21.99),
        new DigitalVideoDisc("La La Land", "Musical", "Damien Chazelle", 128, 14.50),
        new DigitalVideoDisc("The Social Network", "Biography", "David Fincher", 120, 18.90),
        new DigitalVideoDisc("No Country for Old Men", "Thriller", "Joel Coen", 122, 19.25),
        new DigitalVideoDisc("Parasite", "Thriller", "Bong Joon-ho", 132, 25.00),
        new DigitalVideoDisc("Blade Runner 2049", "Science Fiction", "Denis Villeneuve", 164, 28.50),
        new DigitalVideoDisc("Get Out", "Horror", "Jordan Peele", 104, 15.75),
        new DigitalVideoDisc("The Grand Budapest Hotel", "Comedy", "Wes Anderson", 100, 13.00)
    };
    
    private static void logInfo(String message) {
    	System.out.println("[INFO] " + message);
    }
    
    private static void printEmptyLine() {
    	System.out.println();
    }
    
    private static void printCurrentCart(Cart cart) {
    	 logInfo("Current cart:");
    	 System.out.println("=== Total cost: $" + cart.calculateTotalCost() + " ===");
    	 cart.print();
    }
    
    public static void main(String[] args) {
        Cart cart = new Cart();

        logInfo("User adds the first 6 DVDs in the library to cart");
        for (int i = 0; i < 6; i++) {	
            cart.addDVD(availableDVDs[i]);
        }
        printCurrentCart(cart);
        printEmptyLine();
        
        logInfo("User removes the first DVD and fourth DVD");
        cart.removeDVD(availableDVDs[0]);
        cart.removeDVD(availableDVDs[3]);
        printCurrentCart(cart);
        printEmptyLine();
        
        logInfo("User removes a non-existent DVD from the cart");
        cart.removeDVD(availableDVDs[10]);
        logInfo("Technically this behaviour is intended, because after the remove operation, the given DVD is removed from the cart.");
        printCurrentCart(cart);
        printEmptyLine();
        
        logInfo("User removes all of the remaining DVDs from the cart");
        cart.removeDVD(availableDVDs[1]);
        cart.removeDVD(availableDVDs[2]);
        cart.removeDVD(availableDVDs[4]);
        cart.removeDVD(availableDVDs[5]);
        printCurrentCart(cart);
        printEmptyLine();

        
        logInfo("User tries to remove a DVD when the cart is empty");
        cart.removeDVD(availableDVDs[0]);
        printCurrentCart(cart);
        printEmptyLine();

        
        logInfo("User adds 20 DVDs to the cart");
        for (int i = 10; i < 30; i++) {
            cart.addDVD(availableDVDs[i]);
        } 
        printEmptyLine();

        
        logInfo("User tries to add another DVD to a full cart");
        cart.addDVD(availableDVDs[0]);
        printCurrentCart(cart);
        printEmptyLine();
    }
}